vscode:
  extensions:
    - rocketseat.theme-omni@1.0.8:QmhIWMQpQXrQJpxSAckPYw==
    - editorconfig.editorconfig@0.16.4:l0LqpUezIAkfpOEVyymkbA==
    - ahmadawais.shades-of-purple@6.12.0:phtipGVPrS5xO6knvBtr8A==
    - miguelsolorio.fluent-icons@0.0.7:R4J2HS/kiDZvlD956NNV8g==